FROM wordpress:4.6.1-apache

RUN apt-get update && apt-get install -y libmcrypt-dev && docker-php-ext-install mcrypt
RUN curl -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x /usr/local/bin/wp
